config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  resources :users , only: [:show] do
    member do
      get 'notification'
      get 'todo'
      get 'like_history'
      get 'news'
      get 'review_history'
      get 'review_history_great'
      get 'review_history_good'
      get 'review_history_poor'
    end
  end
  resources :payjps, only: [:show, :new, :create]
  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  namespace :purchase_pre do
    resources :items, only: [:show,:update]
  end

  namespace :order_status do
    resources :items, only: [:index,:show] do
      collection do
        get 'pre_index'
      end
    end
  end

  namespace :listings do
    resources :items, only: [:index, :show]
  end

  namespace :in_progress do
    resources :items, only: [:index, :show]
  end

  namespace :completed do
    resources :items, only: [:index, :show]
  end

  namespace :purchase do
    resources :items, only: [:index, :show]
  end

  namespace :purchased do
    resources :items, only: [:index, :show]
  end

  namespace :profile do
    resources :users, only: [:edit, :update]
  end

  get 'mains/profile', to: 'mains#profile'
  get 'mains/card', to: 'mains#card'
  get 'mains/card_new', to: 'mains#creditnew'
  get 'mains/card_after', to: 'mains#creditafter'
  get 'mains/email_password', to: 'mains#email_password'
  get 'mains/identification', to: 'mains#identification'
  get 'mains/sms_confirmation', to: 'mains#sms_confirmation'
  get 'mains/logout', to: 'mains#logout'
  get 'mains/sales_transfer', to: 'mains#sales_transfer'
  get 'mains/points_confirmation', to: 'mains#points_confirmation'
  get 'mains/points_history', to: 'mains#points_history'
  get 'mains/points_limit', to: 'mains#points_limit'
  get 'mains/sales_history', to: 'mains#sales_history'
  get 'mains/sales_tra_lim', to: 'mains#sales_tra_lim'
  get 'mains/sales_tra_bank', to: 'mains#sales_tra_bank'
  get 'mains/sales_tra_history', to: 'mains#sales_tra_history'
  get 'mains/sales_tra_account_register', to: 'mains#sales_tra_account_register'

  get 'mains/top', to: 'mains#mypage'
  get 'mains/notification', to: 'mains#mypage_notification'
  get 'mains/todo', to: 'mains#mypage_todo'
  get 'mains/purchase', to: 'mains#mypage_purchase'
  get 'mains/purchased', to: 'mains#mypage_purchased'
  get 'mains/news', to: 'mains#mypage_news'
  get 'mains/account', to: 'mains#account'

  get 'tests/order_status_waiting', to: 'tests#order_status_waiting'
  get 'tests/account', to: 'tests#account'
  get 'tests/order_status_after_shipping', to: 'tests#order_status_after_shipping'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :postal_code, presence: true, format: { with: /^\d{3}[-]\d{4}$/ , multiline: true }
  validates :area, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true

end

app/models/area.rb
class Area < ApplicationRecord
  has_many :items

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user 
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user

  validates :token, presence: true
end

app/models/image.rb
  class Image < ApplicationRecord
  belongs_to :item, optional: true

  mount_uploader :image, ImagesUploader
end

app/models/item.rb
class Item < ApplicationRecord

  MAX_POST_IMAGES_LENGTH = 4

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category
  belongs_to :size
  belongs_to :brand, optional: true
  belongs_to :area

  accepts_nested_attributes_for :images, allow_destroy: true

  enum condition: %i(brand_new unused great slight_damaged damaged bad)
  enum shipping_payer: %i(seller buyer)
  enum shipping_method: %i(undecided merkari yu_mail letter_pack mail yamato yu_pack click_post yu_packet)
  enum days_to_ship: %i(a_day_two two_three four_seven)

  validates :images, length: {maximum: MAX_POST_IMAGES_LENGTH}
  validates :price, numericality: true, numericality: {greater_than_or_equal_to: 500, less_than: 10000000 }
  validates :name, 
            :text,
            presence: true

  def benefit_from_selling
    (price - 380) * 0.9 
  end

  def selling_fee
    (price - 380) * 0.1
  end
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  
  # validates :email, presence: true, format: {with: /^\S+@\S+\.\S+$/, multiline: true}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

def self.find_for_oauth(auth)
  user = User.where(uid: auth.uid, provider: auth.provider).first

  unless user
    user = User.create(
      nickname:     auth.extra.raw_info.name,
      uid:      auth.uid,
      provider: auth.provider,
      email:    auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
  end

end

  has_many :items, dependent: :destroy
  has_many :comments
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_one :address, dependent: :destroy
  has_one :customer

  validates :email, presence: true, format: { with: /^\S+@\S+\.\S+$/ , multiline: true }
  validates :nickname, presence: true
end

app/controllers/payjps_controller.rb
class PayjpsController < ApplicationController
  before_action :move_to_sign_in
  before_action :move_to_mypage, except: [:show]

  def show
  end

  def new
  end

  def create
    Payjp.api_key = 'sk_test_239330b9aad9f2b589277acb'
    customer = Payjp::Customer.create(
      :card  => params['payjp-token']
    )
    Customer.create(token: customer.id, user_id: current_user.id)
    redirect_to user_path(current_user), notice: 'クレジットカードを登録しました'
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

  def move_to_mypage
    redirect_to user_path(current_user) if current_user.customer.present?
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/payjps_helper.rb
module PayjpsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/testtests_helper.rb
module TesttestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/payjps/new.html.erb
<%= render "shared/header"%>
<main class="l-container clearfix">
  <div class="l-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">クレジットカード登録</h2>
      <div class="l-single-inner">
        <section class="settings-add-card">
          <div class="l-single-content">
            <%= form_tag(action: :create, method: :post) do %>
              <div class="btn-default submit_button">
                 <script type="text/javascript" src="https://checkout.pay.jp" class="payjp-button" data-key="pk_test_7952daf3cca41a190d06666f" data-text="カード番号の登録" data-submit-text="カード番号を登録して閉じる"></script>
              </div>
            <% end %>
          </div>
        </section>
        <div class="settings-not-regist">
          <a href="#" target="_blank">
            <span>支払い方法について</span>
            <i class="icon-arrow-right"></i>
          </a>
        </div>
      </div>
    </section>
  </div>
  <%= render "shared/sidebar" %>
</main>

<%= render "shared/seller-button" %>
<%= render "shared/footer" %>

app/views/payjps/show.html.erb
<%= render "shared/header"%>
<main class="l-container clearfix">
  <div class="l-content">
    <section class="l-chapter-container">
      <% if current_user.customer.present? %>
        <h2 class="l-chapter-head">支払い方法</h2>
        <div class="l-single-inner">
          <section>
            <h2 class="l-chapter-head">登録済み</h2>
          </section>
          <div class="settings-not-regist">
            <a href="#" target="_blank"><span>支払い方法について</span><i class="icon-arrow-right"></i></a>
          </div>
        </div>
      <% else %>
        <h2 class="l-chapter-head">支払い方法</h2>
        <div class="l-single-inner">
          <section>
            <div class="l-single-content">
              <h3 class="l-chapter-sub-head">クレジットカード一覧</h3>
            </div>
            <ul class="settings-payment-list">
            </ul>
          </section>
          <section class="settings-add-card">
            <div class="l-single-content">
              <%= link_to new_payjp_path, class: "btn-default btn-red submit_button" do %>
                <i class="icon-card"></i>
                クレジットカードを追加する
              <% end %>
            </div>
          </section>
          <div class="settings-not-regist">
            <a href="#" target="_blank"><span>支払い方法について</span><i class="icon-arrow-right"></i></a>
          </div>
        </div>
      <% end %>
    </section>
  </div>
  <%= render "shared/sidebar" %>
</main>

<%= render "shared/seller-button" %>
<%= render "shared/footer" %>