config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  resources :users , only: [:show] do
    member do
      get 'notification'
      get 'todo'
      get 'like_history'
      get 'news'
      get 'review_history'
      get 'review_history_great'
      get 'review_history_good'
      get 'review_history_poor'
    end
  end
  resources :payjps, only: [:show, :new, :create]
  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  namespace :purchase_pre do
    resources :items, only: [:show,:update]
  end

  namespace :order_status do
    resources :items, only: [:index,:show] do
      collection do
        get 'pre_index'
      end
    end
  end

  namespace :listings do
    resources :items, only: [:index, :show]
  end

  namespace :in_progress do
    resources :items, only: [:index, :show]
  end

  namespace :completed do
    resources :items, only: [:index, :show]
  end

  namespace :purchase do
    resources :items, only: [:index, :show]
  end

  namespace :purchased do
    resources :items, only: [:index, :show]
  end

  namespace :profile do
    resources :users, only: [:edit, :update]
  end

  get 'mains/profile', to: 'mains#profile'
  get 'mains/card', to: 'mains#card'
  get 'mains/card_new', to: 'mains#creditnew'
  get 'mains/card_after', to: 'mains#creditafter'
  get 'mains/email_password', to: 'mains#email_password'
  get 'mains/identification', to: 'mains#identification'
  get 'mains/sms_confirmation', to: 'mains#sms_confirmation'
  get 'mains/logout', to: 'mains#logout'
  get 'mains/sales_transfer', to: 'mains#sales_transfer'
  get 'mains/points_confirmation', to: 'mains#points_confirmation'
  get 'mains/points_history', to: 'mains#points_history'
  get 'mains/points_limit', to: 'mains#points_limit'
  get 'mains/sales_history', to: 'mains#sales_history'
  get 'mains/sales_tra_lim', to: 'mains#sales_tra_lim'
  get 'mains/sales_tra_bank', to: 'mains#sales_tra_bank'
  get 'mains/sales_tra_history', to: 'mains#sales_tra_history'
  get 'mains/sales_tra_account_register', to: 'mains#sales_tra_account_register'

  get 'mains/top', to: 'mains#mypage'
  get 'mains/notification', to: 'mains#mypage_notification'
  get 'mains/todo', to: 'mains#mypage_todo'
  get 'mains/purchase', to: 'mains#mypage_purchase'
  get 'mains/purchased', to: 'mains#mypage_purchased'
  get 'mains/news', to: 'mains#mypage_news'
  get 'mains/account', to: 'mains#account'

  get 'tests/order_status_waiting', to: 'tests#order_status_waiting'
  get 'tests/account', to: 'tests#account'
  get 'tests/order_status_after_shipping', to: 'tests#order_status_after_shipping'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :postal_code, presence: true, format: { with: /^\d{3}[-]\d{4}$/ , multiline: true }
  validates :area, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true

end

app/models/area.rb
class Area < ApplicationRecord
  has_many :items

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user 
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user

  validates :token, presence: true
end

app/models/image.rb
  class Image < ApplicationRecord
  belongs_to :item, optional: true

  mount_uploader :image, ImagesUploader
end

app/models/item.rb
class Item < ApplicationRecord

  MAX_POST_IMAGES_LENGTH = 4

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category
  belongs_to :size
  belongs_to :brand, optional: true
  belongs_to :area

  accepts_nested_attributes_for :images, allow_destroy: true

  enum condition: %i(brand_new unused great slight_damaged damaged bad)
  enum shipping_payer: %i(seller buyer)
  enum shipping_method: %i(undecided merkari yu_mail letter_pack mail yamato yu_pack click_post yu_packet)
  enum days_to_ship: %i(a_day_two two_three four_seven)

  validates :images, length: {maximum: MAX_POST_IMAGES_LENGTH}
  validates :price, numericality: true, numericality: {greater_than_or_equal_to: 500, less_than: 10000000 }
  validates :name, 
            :text,
            presence: true

  def benefit_from_selling
    (price - 380) * 0.9 
  end

  def selling_fee
    (price - 380) * 0.1
  end
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  
  # validates :email, presence: true, format: {with: /^\S+@\S+\.\S+$/, multiline: true}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

def self.find_for_oauth(auth)
  user = User.where(uid: auth.uid, provider: auth.provider).first

  unless user
    user = User.create(
      nickname:     auth.extra.raw_info.name,
      uid:      auth.uid,
      provider: auth.provider,
      email:    auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
  end

end

  has_many :items, dependent: :destroy
  has_many :comments
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_one :address, dependent: :destroy
  has_one :customer

  validates :email, presence: true, format: { with: /^\S+@\S+\.\S+$/ , multiline: true }
  validates :nickname, presence: true
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/payjps_helper.rb
module PayjpsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_footer.html.erb
<aside class="app-banner" height="260" background-center="position">
  <div class="app-banner-pc">
    <div class="app-banner-pc-inner" height="165.76" width="420">
      <h2>スマホでかんたんフリマアプリ</h2>
      <p>今すぐ無料ダウンロード!</p>
      <div class="app-banner-icon clearfix">
        <figure>
          <a href="#">
            <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3913698104" width="68" height="68" alt>
          </a>
        </figure>
        <ul class="clearfix">
          <li>
            <a href="#" target="_blank">
              <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3913698104" alt width="133" height="40">
            </a>
          </li>
          <li>
            <a href="#" target="_blank">
              <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3913698104" alt width="133" height="40">
            </a>
          </li>
        </ul>
      </div>
    </div>
    <figure class="smart-phone-app">
      <a href="#">
        <img src="https://www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3913698104" alt width="300" height="260">
      </a>
    </figure>
  </div>
</aside>

<footer class="global-footer">
     <nav>
       <ul>
         <li class="download-app">
           <a href="">
             <img src="">
             "今すぐ無料ダウンロード"
           </a>
         </li>
         <li class="footer-cell">
           <h2 class="footer-head">メルカリについて</h2>
           <ul>
             <li>
               <a href="">会社概要（運営会社）</a>
             </li>
             <li>
               <a href="">プライバシーポリシー</a>
             </li>
             <li>
               <a href="">メルカリ利用規約</a>
             </li>
             <li>
               <a href="">メルカリ利用規約・有償ポイントに関する特約</a>
             </li>
             <li>
               <a href="">あんしんスマホサポート制度に関する利用特約</a>
             </li>
             <li>
               <a href="">コンプライアンスポリシー</a>
             </li>
             <li>
               <a href="">個人データの安全管理に係る基本方針</a>
             </li>
             <li>
               <a href="">特定商取引に関する表記</a>
             </li>
             <li>
               <a href="">資金決済法に基づく表示</a>
             </li>
             <li>
               <a href="">法令遵守と犯罪抑止の為に</a>
             </li>
             <li>
               <a href="">採用情報</a>
             </li>
           </ul>
         </li>

         <li class="footer-cell">
           <h2 class="footer-head">メルカリを見る</h2>
           <ul>
             <li>
               <a href="">カテゴリー一覧</a>
             </li>
             <li>
               <a href="">ブランド一覧</a>
             </li>
             <li>
               <a href="">出品地域一覧</a>
             </li>
             <li>
               <a href="">公式ブログ</a>
             </li>
             <li>
               <a href="">公式Twitter</a>
             </li>
             <li>
               <a href="">公式Facebook</a>
             </li>
           </ul>
         </li>
         <li class="footer-cell">
           <h2 class="footer-head">ヘルプ＆ガイド</h2>
           <ul>
             <li>
               <a href="">メルカリガイド</a>
             </li>
             <li>
               <a href="">メルカリロゴ利用ガイドライン</a>
             </li>
             <li>
               <a href="">お知らせ</a>
             </li>
             <li>
               <a href="">らくらくメルカリ便とは</a>
             </li>
             <li>
               <a href="">ゆうゆうメルカリ便とは</a>
             </li>
             <li>
               <a href="">大型らくらくメルカリ便とは</a>
             </li>
             <li>
               <a href="">車体取引ガイド</a>
             </li>
             <li>
               <a href="">返品・返金ポリシー</a>
             </li>
             <li>
               <a href="">メルカリあんしん・あんぜん宣言</a>
             </li>
             <li>
               <a href="">偽ブランド品撲滅への取り組み</a>
             </li>
             <li>
               <a href="">メルカリボックス</a>
             </li>
           </ul>
         </li>
         <li class="footer-cell">
           <h2 class="footer-head">国</h2>
           <ul class="footer-nav-lang">
             <li>
               <a href="">
                 <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?815696604" alt="" width="22">
                 United States
               </a>
             </li>
             <li>
               <a href="">
                 <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?815696604" alt="" width="22">
                 United Kingdom
               </a>
             </li>
             <li>
               <a href="" class="active">
                 <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?815696604" alt="" width="22">
                 日本
               </a>
             </li>
           </ul>
         </li>
       </ul>
     </nav>
     <a href="" class="footer-logo">
       <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?815696604" width="124" height="33" alt="mercari">
     </a>
     <p class="footer-copyright">
       <small>© 2018 Mercari</small>
     </p>
</footer>

app/views/shared/_head-banner.html.erb
<section class="top-main-visual">
  <div class="top-banner">
  <div class="top-main-visual-content">
      <h2 class="font-white">
        スマホでかんたんフリマアプリ
      </h2>
      <p class="font-white">
        メルカリはスマホカメラからすぐに出品できる<br>
        購入時も安心な独自システムのアプリです
      </p>
      <div class="top-main-visual-store clearfix">
        <ul class="clearfix">
          <li>
            <a href="#" target="_blank">
              <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3913698104" alt="" width="170" height="50.3">
            </a>
          </li>
          <li>
            <a href="#" target="_blank">
              <img src="https://www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3913698104" alt="" width="170" height="50.3">
            </a>
          </li>
        </ul>
      </div>
    </div>
    <figure class="smart-phone-app">
      <img src="https://www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?3913698104" alt="" width="480" height="390">
    </figure>
  </div>
  </div>
</section>

app/views/shared/_order_status_sidebar.html.erb
<div class="l-side">
  <section class="l-side-container">
    <h3 class="transact-info-head">取引情報</h3>
    <div class="transact-info-inner">
      <ul class="transact-info-table">
              <li class="transact-info-table-row">
          <span class="transact-info-table-cell">商品</span>
          <ul class="transact-info-table-cell">
            <li>
              <a href="https://static-mercari-jp-imgtr2.akamaized.net/item/detail/orig/photos/m38566204988_1.jpg?1537838737">
                <% @item.images.first(1).each do |content| %>
                  <%= image_tag content.image, class: "lazyload", alt: "" %>
                <% end %>
                
                <div class="transact-info-item bold">
                  <%= @item.name %>
                  <br>
                  ¥ <%= number_with_delimiter(@item.price) %>
                </div>
              </a>
            </li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">送料</span>
          <ul class="transact-info-table-cell">
            <li>
              送料込み(出品者負担)
            </li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">販売手数料</span>
          <ul class="transact-info-table-cell">
            <li>¥ <%= @item.selling_fee.floor %></li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">配送料</span>
          <ul class="transact-info-table-cell">
            <li>¥ 380</li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">販売利益</span>
          <ul class="transact-info-table-cell">
            <li>
              ¥ <%= @item.benefit_from_selling.floor %>
            </li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">購入日時</span>
          <ul class="transact-info-table-cell">
            <li><%= @item.updated_at.to_s(:purchased_at) %></li>
          </ul>
        </li>
        <li class="transact-info-table-row">
          <span class="transact-info-table-cell">商品ID</span>
          <ul class="transact-info-table-cell">
            <li>m38566204988</li>
          </ul>
        </li>   
      </ul>
  </section>

  <section class="l-side-container">
    <h3 class="transact-info-head">購入者情報</h3>
    <div class="transact-info-inner">
      <a href="#" class="transaction-user-icon">
        <figure>
          <figure>
            <div>
              <img src="https://static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage.png" alt="" width="40">
            </div>
          <figcaption class="bold">
            <div class="transact-user-name">
              <%= @item.seller.nickname %>
            </div>
          </figcaption>
        </figure>
        <i class="material-icons">keyboard_arrow_right</i>
      </a>
    </div>
    <br>
  </section>
  <div class="l-visible-large">
    <a href="https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8" target="_blank" class="side-banner">
      <img src="//www-mercari-jp.akamaized.net/assets/img/common/jp/side_banner.jpg?3276806293" alt="Download Mercari Now">
    </a>
  </div>
</div>

app/views/shared/_seller-button.html.erb
<%= link_to new_item_path, class: "footer-sell-btn" do %>
  <div class="seller-button">出品</div>
  <i class="fas fa-camera"></i>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="l-side">
  <nav class="mypage-nav">
    <ul class="mypage-nave-list", style="list-style: none;">
      <li>
        <%= link_to user_path(current_user), class: "mypage-nav-list-item" do %>
          マイページ
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to notification_user_path(current_user), class: "mypage-nav-list-item" do %>
          お知らせ
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to todo_user_path(current_user), class: "mypage-nav-list-item" do %>
          やることリスト
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to like_history_user_path(current_user), class: "mypage-nav-list-item" do %>
          いいね！一覧
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <a href="" class="mypage-nav-list-item ">
          LIVE配信
          <i class="fas fa-angle-right"></i>
        </a>
      </li>
      <li>
        <%= link_to new_item_path, class: "mypage-nav-list-item" do %>
          出品する
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to listings_items_path, class: "mypage-nav-list-item" do %>
          出品した商品-出品中
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to in_progress_items_path, class: "mypage-nav-list-item" do %>
          出品した商品-取引中
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to completed_items_path, class: "mypage-nav-list-item" do %>
          出品した商品-売却済み
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to purchase_items_path, class: "mypage-nav-list-item" do %>
          購入した商品-取引中
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to purchased_items_path, class: "mypage-nav-list-item" do %>
          購入した商品-過去の取引
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to news_user_path(current_user), class: "mypage-nav-list-item" do %>
          ニュース一覧
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to review_history_user_path(current_user), class: "mypage-nav-list-item" do %>
          評価一覧
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <a href="" class="mypage-nav-list-item ">
          ガイド
          <i class="fas fa-angle-right"></i>
        </a>
      </li>
      <li>
        <a href="" class="mypage-nav-list-item ">
          お問い合わせ
          <i class="fas fa-angle-right"></i>
        </a>
      </li>
    <!-- </ul> -->
        <h3 class="mypage-nav-head">売上・ポイント</h3>
    <!-- <ul class="mypage-nav-list", style="list-style: none;"> -->
      <li>
        <a href="/order_status/items/pre_index" class="mypage-nav-list-item ">
          売上・振込申請
      <i class="fas fa-angle-right"></i>
      </a>
    </li>
      <li>
        <a href="/mains/points_confirmation/" class="mypage-nav-list-item ">
          ポイント
      <i class="fas fa-angle-right"></i>
      </a>
    </li>
  <h3 class="mypage-nav-head">設定</h3>
      <li>
        <%= link_to edit_profile_user_path(current_user), class: "mypage-nav-list-item" do %>
          プロフィール
          <i class="fas fa-angle-right"></i>
        <% end %>
    </li>
      <li>
          <div class="mypage-nav-list-item" >
            <%= link_to "住所変更", new_address_path, class: "link"%>
            <i class="fas fa-angle-right"></i>
          </div>
       <!--  <a href="/addresses/new" class="mypage-nav-list-item "> -->
    </li>
      <li>
        <%= link_to payjp_path(current_user), class: "mypage-nav-list-item" do %>
          支払い方法
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <%= link_to edit_user_registration_path, class: "mypage-nav-list-item" do %>
          メール/パスワード
          <i class="fas fa-angle-right"></i>
        <% end %>
      </li>
      <li>
        <a href="/mains/identification" class="mypage-nav-list-item ">
          本人情報
      <i class="fas fa-angle-right"></i>
    </a>
    </li>
      <li>
        <a href="/mains/sms_confirmation" class="mypage-nav-list-item ">
          電話番号の確認
      <i class="fas fa-angle-right"></i>
    </a>
    </li>
      <li>
        <a href="/mains/logout" class="mypage-nav-list-item ">
          ログアウト
      <i class="fas fa-angle-right"></i>
    </a>
    </li>
  </ul>
  </nav>
<div class="l-visible-large">
  <a href="https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8" target="_blank" class="side-banner">
  <img src="https://www-mercari-jp.akamaized.net/assets/img/common/jp/side_banner.jpg?815696604" class=" styleimage">
  </a>
</div>
</div>

app/views/shared/_single-footer.html.erb
 <footer class="single-footer">
  <nav>
    <ul class="clearfix">
      <li>
        <a href="https://www.mercari.com/jp/privacy/">プライバシーポリシー</a>
      </li>
      <li>
        <a href="https://www.mercari.com/jp/tos/">メルカリ利用規約</a>
      </li>
      <li>
        <a href="https://www.mercari.com/jp/tokutei/">特定商取引に関する表記</a>
      </li>
    </ul>
  </nav>
  <a href="https://www.mercari.com/jp/" class="single-footer-logo">
    <img src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?2834800195" alt="mercari" width="80" height="65">
  </a>
  <p>
    <small>&copy; 2018 Mercari</small>
  </p>
</footer>

app/views/shared/_single-header.html.erb
<header class="single-header">
	<h1>
	  <a href="https://www.mercari.com/jp/">
	    <img src="//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2834800195" alt="mercari">
	  </a>
	</h1>
</header>