config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  resources :users , only: [:show] do
    member do
      get 'notification'
      get 'todo'
      get 'like_history'
      get 'news'
      get 'review_history'
      get 'review_history_great'
      get 'review_history_good'
      get 'review_history_poor'
    end
  end
  resources :payjps, only: [:show, :new, :create]
  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  namespace :purchase_pre do
    resources :items, only: [:show,:update]
  end

  namespace :order_status do
    resources :items, only: [:index,:show] do
      collection do
        get 'pre_index'
      end
    end
  end

  namespace :listings do
    resources :items, only: [:index, :show]
  end

  namespace :in_progress do
    resources :items, only: [:index, :show]
  end

  namespace :completed do
    resources :items, only: [:index, :show]
  end

  namespace :purchase do
    resources :items, only: [:index, :show]
  end

  namespace :purchased do
    resources :items, only: [:index, :show]
  end

  namespace :profile do
    resources :users, only: [:edit, :update]
  end

  get 'mains/profile', to: 'mains#profile'
  get 'mains/card', to: 'mains#card'
  get 'mains/card_new', to: 'mains#creditnew'
  get 'mains/card_after', to: 'mains#creditafter'
  get 'mains/email_password', to: 'mains#email_password'
  get 'mains/identification', to: 'mains#identification'
  get 'mains/sms_confirmation', to: 'mains#sms_confirmation'
  get 'mains/logout', to: 'mains#logout'
  get 'mains/sales_transfer', to: 'mains#sales_transfer'
  get 'mains/points_confirmation', to: 'mains#points_confirmation'
  get 'mains/points_history', to: 'mains#points_history'
  get 'mains/points_limit', to: 'mains#points_limit'
  get 'mains/sales_history', to: 'mains#sales_history'
  get 'mains/sales_tra_lim', to: 'mains#sales_tra_lim'
  get 'mains/sales_tra_bank', to: 'mains#sales_tra_bank'
  get 'mains/sales_tra_history', to: 'mains#sales_tra_history'
  get 'mains/sales_tra_account_register', to: 'mains#sales_tra_account_register'

  get 'mains/top', to: 'mains#mypage'
  get 'mains/notification', to: 'mains#mypage_notification'
  get 'mains/todo', to: 'mains#mypage_todo'
  get 'mains/purchase', to: 'mains#mypage_purchase'
  get 'mains/purchased', to: 'mains#mypage_purchased'
  get 'mains/news', to: 'mains#mypage_news'
  get 'mains/account', to: 'mains#account'

  get 'tests/order_status_waiting', to: 'tests#order_status_waiting'
  get 'tests/account', to: 'tests#account'
  get 'tests/order_status_after_shipping', to: 'tests#order_status_after_shipping'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :postal_code, presence: true, format: { with: /^\d{3}[-]\d{4}$/ , multiline: true }
  validates :area, presence: true
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :family_name_kana, presence: true
  validates :first_name_kana, presence: true

end

app/models/area.rb
class Area < ApplicationRecord
  has_many :items

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user 
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user

  validates :token, presence: true
end

app/models/image.rb
  class Image < ApplicationRecord
  belongs_to :item, optional: true

  mount_uploader :image, ImagesUploader
end

app/models/item.rb
class Item < ApplicationRecord

  MAX_POST_IMAGES_LENGTH = 4

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category
  belongs_to :size
  belongs_to :brand, optional: true
  belongs_to :area

  accepts_nested_attributes_for :images, allow_destroy: true

  enum condition: %i(brand_new unused great slight_damaged damaged bad)
  enum shipping_payer: %i(seller buyer)
  enum shipping_method: %i(undecided merkari yu_mail letter_pack mail yamato yu_pack click_post yu_packet)
  enum days_to_ship: %i(a_day_two two_three four_seven)

  validates :images, length: {maximum: MAX_POST_IMAGES_LENGTH}
  validates :price, numericality: true, numericality: {greater_than_or_equal_to: 500, less_than: 10000000 }
  validates :name, 
            :text,
            presence: true

  def benefit_from_selling
    (price - 380) * 0.9 
  end

  def selling_fee
    (price - 380) * 0.1
  end
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items

end

app/models/user.rb
class User < ApplicationRecord
  
  # validates :email, presence: true, format: {with: /^\S+@\S+\.\S+$/, multiline: true}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

def self.find_for_oauth(auth)
  user = User.where(uid: auth.uid, provider: auth.provider).first

  unless user
    user = User.create(
      nickname:     auth.extra.raw_info.name,
      uid:      auth.uid,
      provider: auth.provider,
      email:    auth.info.email,
      password: Devise.friendly_token[0, 20]
    )
  end

end

  has_many :items, dependent: :destroy
  has_many :comments
  has_many :buyed_items, foreign_key: "buyer_id", class_name: "Item"
  has_many :selling_items, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_many :sold_items, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Item"
  has_one :address, dependent: :destroy
  has_one :customer

  validates :email, presence: true, format: { with: /^\S+@\S+\.\S+$/ , multiline: true }
  validates :nickname, presence: true
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :set_credit, only: [:destroy]

  def index
    @credit = Credit.find_by(user_id: current_user.id)
  end

  def new
    @credit = Credit.new
  end

  def create
    Credit.create(credit_params)
    redirect_to mains_top_path
  end

  def destroy
    @credit.destroy
    redirect_to mains_top_path
  end

  private

  def credit_params
    params.require(:credit).permit(:num, :expire_month, :expire_year, :security_code).merge(user_id: current_user.id)
  end

  def set_credit
    @credit = Credit.find(params[:id])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/payjps_helper.rb
module PayjpsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/testtests_helper.rb
module TesttestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credits/index.html.erb
<%= render "shared/header"%>
<main class="l-container clearfix">
  <div class="l-content">
    <section class="l-chapter-container">
      <% if @credit %>
        <h2 class="l-chapter-head">支払い方法</h2>
        <div class="notification notification-success">
          追加しました。
          <i class="icon-close"></i>
        </div>
        <div class="l-single-inner">
          <section>
            <div class="l-single-content">
              <h3 class="l-chapter-sub-head">クレジットカード一覧</h3>
            </div>
            <ul class="settings-payment-list">
              <li>
                <!-- <form class="l-single-content" action="https://www.mercari.com/jp/mypage/card/delete/" method="POST"> -->
                <div class="l-single-content">
                  <figure>
                    <img src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?255148577" width="49" height="15" alt="visa">
                  </figure>
                  <!-- <input type="hidden" name="__csrf_value" value="93de52ee26bfd5824d9711425b5e66252f2408ef77cfb172a63569f01112ac3b4b530e75477b2e20bbdb29bd71422a989ba9d42fd2a89c9ca6311a6803f82a665"> -->
                  <!-- <input type="hidden" name="card_sequence_no" value="3"> -->
                  <!-- <div class="settings-payment-num">************4485</div> -->
                  <div class="settings-payment-num"><%= @credit.num %></div>
                  <!-- <div class="settings-payment-num">07 / 21 </div> -->
                  <div class="settings-payment-num"><%= @credit.expire_month %> / <%= @credit.expire_year %></div>
                  <!-- <input type="hidden" name="method" value="card"> -->
  <!--                 <button type="submit" class="settings-payment-remove">
                    削除する
                  </button> -->
                  <button class="settings-payment-remove">
                    <%= link_to '削除する', "/credits/#{@credit.id}", method: :delete %>
                  </button>
                <!-- </form> -->
                </div>
              </li>
            </ul>
          </section>
          <div class="settings-not-regist">
            <a href="/jp/help_center/category/6/" target="_blank"><span>支払い方法について</span><i class="icon-arrow-right"></i></a>
          </div>
        </div>
      <% else %>
        <h2 class="l-chapter-head">支払い方法</h2>
        <div class="l-single-inner">
          <section>
            <div class="l-single-content">
              <h3 class="l-chapter-sub-head">クレジットカード一覧</h3>
            </div>
            <ul class="settings-payment-list">
            </ul>
          </section>
          <section class="settings-add-card">
            <div class="l-single-content">
              <!-- <a href="https://www.mercari.com/jp/mypage/card/create/" class="btn-default btn-red submit_button "> -->
              <%= link_to new_credit_path, class: "btn-default btn-red submit_button" do %>
                <i class="icon-card"></i>クレジットカードを追加する
              <!-- </a> -->
              <% end %>
            </div>
          </section>
          <div class="settings-not-regist">
            <a href="/jp/help_center/category/6/" target="_blank">
              <span>支払い方法について</span>
              <i class="icon-arrow-right"></i>
            </a>
          </div>
        </div>
      <% end %>
    </section>
  </div>
  <%= render "shared/sidebar" %>
</main>

<%= render "shared/seller-button" %>
<%= render "shared/footer" %>


link_to '削除', "/prototypes/#{@prototype.id}", method: :delete, class: 'btn-default btn'

app/views/credits/new.html.erb
<%= render "shared/header"%>
<main class="l-container clearfix">
  <div class="l-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">クレジットカード情報入力</h2>
      <%= form_for @credit, html: {class: 'l-single-inner'} do |f| %>
        <div class="l-single-content">
          <div class="form-group">
            <%= f.label :num, "カード番号" %>
            <span class="form-require">必須</span>
            <%= f.text_field :num, autofocus: true, class: 'input-default', placeholder: "半角数字のみ", maxlength: "19" %>
            <ul id="card-no-error-wrapper" class="has-error-text"></ul>
            <ul class="signup-card-list">
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?255148577" width="49" height="20" alt="">
              </li>
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?255148577" width="34" height="20" alt="">
              </li>
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?255148577" width="30" height="20" alt="">
              </li>
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?255148577" width="32" height="20" alt="">
              </li>
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?255148577" width="32" height="20" alt="">
              </li>
              <li>
                <img src="//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?255148577" width="32" height="20" alt="">
              </li>
            </ul>
          </div>

          <div class="form-group signup-form-expire">
            <%= f.label :expire_month, "有効期限" %>
            <span class="form-require">必須</span>
            <br>
            <div class="select-wrap">
              <%= f.select :expire_month, [["01", "01"], ["02", "02"], ["03", "04"], ["04", "04"], ["05", "05"], ["06", "06"], ["07", "07"], ["08", "08"], ["09", "09"], ["10", "10"], ["11", "11"], ["12", "12"]], {}, { class: 'select-default' } %>
              <i class="icon-arrow-bottom"></i>
            </div>
            <span>月</span>
            <ul id="expire-mm-error-wrapper" class="has-error-text"></ul>
            <div class="select-wrap">
              <%= f.select :expire_year, [["18", "18"], ["19", "19"], ["20", "20"], ["21", "21"], ["23", "23"], ["24", "24"], ["25", "25"], ["26", "26"], ["27", "27"], ["28", "28"]], {}, { class: 'select-default' } %>
              <i class="icon-arrow-bottom"></i>
            </div>
            <span>年</span>
            <ul id="expire-yy-error-wrapper" class="has-error-text"></ul>
          </div>

          <div class="form-group">
            <%= f.label :security_code, "セキュリティコード" %>
            <span class="form-require">必須</span>
            <%= f.text_field :security_code, class: 'input-default', placeholder: "カード背面4桁もしくは3桁の番号" %>
            <ul id="security-code-error-wrapper" class="has-error-text"></ul>
            <div class="signup-seqcode">
              <div class="signup-seqcode-text" data-js="show-tips-toggle">
                <span class="form-question">?</span>カード裏面の番号とは？
              </div>
              <div class="signup-seqcode-info" data-js="show-tips-content">
                カードの裏面をご参照ください。
                <br>
                <img src="//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?255148577" alt="" width="240">
              </div>
            </div>
          </div>
          <p id="primary-error" class="has-error-text"></p>
          <%= f.submit "追加する", class: 'btn-default btn-red' %>
        </div>
        <script type="text/javascript" async="" src="https://www.google-analytics.com/plugins/ua/ec.js"></script>
        <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
        <script type="text/javascript" async="" src="//www.googleadservices.com/pagead/conversion_async.js"></script>
        <script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-KLPT5L5"></script>
        <script src="https://p01.mul-pay.jp/ext/js/token.js" async=""></script>
        <script src="//www-mercari-jp.akamaized.net/assets/js/get_gmopg_card_token.js?736512970" async=""></script>
        <script src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/880621981/?random=1539162080863&amp;cv=9&amp;fst=1539162080863&amp;num=1&amp;guid=ON&amp;resp=GooglemKTybQhCsO&amp;eid=659255991&amp;u_h=900&amp;u_w=1440&amp;u_ah=825&amp;u_aw=1440&amp;u_cd=24&amp;u_his=50&amp;u_tz=540&amp;u_java=false&amp;u_nplug=3&amp;u_nmime=4&amp;gtm=Ga1&amp;sendb=1&amp;frm=0&amp;url=https%3A%2F%2Fwww.mercari.com%2Fjp%2Fmypage%2Fcard%2Fcreate%2F&amp;ref=https%3A%2F%2Fwww.mercari.com%2Fjp%2Fmypage%2Fcard%2F&amp;tiba=%E3%82%AF%E3%83%AC%E3%82%B8%E3%83%83%E3%83%88%E3%82%AB%E3%83%BC%E3%83%89%E6%83%85%E5%A0%B1%E5%85%A5%E5%8A%9B%20-%20%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA%20%E3%82%B9%E3%83%9E%E3%83%9B%E3%81%A7%E3%81%8B%E3%82%93%E3%81%9F%E3%82%93%20%E3%83%95%E3%83%AA%E3%83%9E&amp;async=1&amp;rfmt=3&amp;fmt=4"></script>
      <% end %>
    </section>
  </div>
  <%= render "shared/sidebar" %>
</main>

<%= render "shared/seller-button" %>
<%= render "shared/footer" %>