config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'items#index'
  resources :users , only: [:show] do
    member do
      get 'notification'
      get 'todo'
      get 'like_history'
      get 'news'
      get 'review_history'
      get 'review_history_great'
      get 'review_history_good'
      get 'review_history_poor'
    end
  end
  resources :payjps, only: [:show, :new, :create]
  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credits, only: [:index, :new, :create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    resources :comments, only: [:show, :create, :edit, :update, :destroy]
  end
  resources :categories, only: [:show]
  resources :brands, only: [:show]

  namespace :purchase_pre do
    resources :items, only: [:show,:update]
  end

  namespace :order_status do
    resources :items, only: [:index,:show] do
      collection do
        get 'pre_index'
      end
    end
  end

  namespace :listings do
    resources :items, only: [:index, :show]
  end

  namespace :in_progress do
    resources :items, only: [:index, :show]
  end

  namespace :completed do
    resources :items, only: [:index, :show]
  end

  namespace :purchase do
    resources :items, only: [:index, :show]
  end

  namespace :purchased do
    resources :items, only: [:index, :show]
  end

  namespace :profile do
    resources :users, only: [:edit, :update]
  end

  get 'mains/profile', to: 'mains#profile'
  get 'mains/card', to: 'mains#card'
  get 'mains/card_new', to: 'mains#creditnew'
  get 'mains/card_after', to: 'mains#creditafter'
  get 'mains/email_password', to: 'mains#email_password'
  get 'mains/identification', to: 'mains#identification'
  get 'mains/sms_confirmation', to: 'mains#sms_confirmation'
  get 'mains/logout', to: 'mains#logout'
  get 'mains/sales_transfer', to: 'mains#sales_transfer'
  get 'mains/points_confirmation', to: 'mains#points_confirmation'
  get 'mains/points_history', to: 'mains#points_history'
  get 'mains/points_limit', to: 'mains#points_limit'
  get 'mains/sales_history', to: 'mains#sales_history'
  get 'mains/sales_tra_lim', to: 'mains#sales_tra_lim'
  get 'mains/sales_tra_bank', to: 'mains#sales_tra_bank'
  get 'mains/sales_tra_history', to: 'mains#sales_tra_history'
  get 'mains/sales_tra_account_register', to: 'mains#sales_tra_account_register'

  get 'mains/top', to: 'mains#mypage'
  get 'mains/notification', to: 'mains#mypage_notification'
  get 'mains/todo', to: 'mains#mypage_todo'
  get 'mains/purchase', to: 'mains#mypage_purchase'
  get 'mains/purchased', to: 'mains#mypage_purchased'
  get 'mains/news', to: 'mains#mypage_news'
  get 'mains/account', to: 'mains#account'

  get 'tests/order_status_waiting', to: 'tests#order_status_waiting'
  get 'tests/account', to: 'tests#account'
  get 'tests/order_status_after_shipping', to: 'tests#order_status_after_shipping'

end

app/models/item.rb
class Item < ApplicationRecord

  MAX_POST_IMAGES_LENGTH = 4

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :category
  belongs_to :size
  belongs_to :brand, optional: true
  belongs_to :area

  accepts_nested_attributes_for :images, allow_destroy: true

  enum condition: %i(brand_new unused great slight_damaged damaged bad)
  enum shipping_payer: %i(seller buyer)
  enum shipping_method: %i(undecided merkari yu_mail letter_pack mail yamato yu_pack click_post yu_packet)
  enum days_to_ship: %i(a_day_two two_three four_seven)

  validates :images, length: {maximum: MAX_POST_IMAGES_LENGTH}
  validates :price, numericality: true, numericality: {greater_than_or_equal_to: 500, less_than: 10000000 }
  validates :name, 
            :text,
            presence: true

  def benefit_from_selling
    (price - 380) * 0.9 
  end

  def selling_fee
    (price - 380) * 0.1
  end
end

app/controllers/completed/items_controller.rb
class Completed::ItemsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @items = Item.where(seller_id: current_user.id).where.not(buyer_id: nil).where(trading_status: 1)
  end

  def show
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/in_progress/items_controller.rb
class InProgress::ItemsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @items = Item.where(seller_id: current_user.id).where.not(buyer_id: nil).where(trading_status: 0)
  end

  def show
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit]
  before_action :move_to_sign_in, only: [:new]
  before_action :user_check, only: [:update, :destroy]

  def index
    @ladies = Item.where(category_id: 1).order("created_at DESC").limit(4)
    @mens = Item.where(category_id: 2).order("created_at DESC").limit(4)
    @cosmes = Item.order("created_at DESC").limit(4)
    @babies = Item.where(category_id: 3).order("created_at DESC").limit(4)
    @chanels = Item.where(brand_id: 1).order("created_at DESC").limit(4)
    @supremes = Item.where(brand_id: 28).order("created_at DESC").limit(4)
    @nikes = Item.order("created_at DESC").limit(4)
  end

  def show
    @images = @item.images
    @comments = @item.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @item = Item.new
    4.times { @item.images.build }  # 1つのitemにつき最大4つの画像を持たせる
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to :root, notice: '出品しました'
    else
      redirect_to :new_item , alert: '出品に失敗しました'
    end
  end

  def edit
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params) 
      redirect_to :root, notice: '編集に成功しました'
    else
      redirect_to :edit_item , alert: '編集に失敗しました'
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy 
    redirect_to :root, notice: '商品を削除しました'
  end

  def search
    @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%").limit(8)
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :text,
      :price,
      :condition,
      :shipping_payer,
      :shipping_method,
      :days_to_ship,
      :trading_status,
      :shipping_fee,
      :category_id,
      :brand_id,
      :size_id,
      :area_id,
      :seller_id,
      :buyer_id,
      images_attributes: [:id, :image, :item_id, :_destroy]
    )
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
  
  def user_check
    item = Item.find(params[:id])
    redirect_to root_path, alert: '商品情報の編集は出品者のみ可能です' unless item.seller_id == current_user.id
  end
end

app/controllers/listings/items_controller.rb
class Listings::ItemsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @items = Item.where(seller_id: current_user.id).where(buyer_id: nil)
  end

  def show
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/order_status/items_controller.rb
class OrderStatus::ItemsController < ApplicationController

  def index
    @items = current_user.sold_items
  end

  def show
    @item = Item.find(params[:id])
  end

  def pre_index
    @items = current_user.sold_items
    render 'sales_transfer'
  end
end

app/controllers/purchase/items_controller.rb
class Purchase::ItemsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @items = Item.where(buyer_id: current_user.id).where(trading_status: 0)
  end

  def show
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/purchase_pre/items_controller.rb
class PurchasePre::ItemsController < ApplicationController
  before_action :move_to_sign_in, :move_to_new_address
  before_action :move_to_new_payjp

  def show
  	@item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])

    if current_user.id == item.seller_id
      redirect_to root_path, alert: '出品者と購入者が同じです。商品を再度選択してください。'
    else
      item.update(item_params) 
      
      amount = item.price
      customer = Customer.find_by(user_id: current_user.id)
      customer = customer.token
      Payjp.api_key = 'sk_test_239330b9aad9f2b589277acb'
      Payjp::Charge.create(
        amount:   amount,
        customer: customer,
        currency: 'jpy'
      )

      @item = Item.find(params[:id])
      render 'purchase_confirmation'
    end
  end

  private

  def item_params
    params.require(:item).permit(:buyer_id)
  end

  def move_to_sign_in
    redirect_to new_user_session_path, alert: '購入前にログインを行なってください' unless user_signed_in?
  end

  def move_to_new_address
    redirect_to new_address_path, alert: '購入前に住所を登録してください' unless current_user.address.present?
  end
    
  def move_to_new_payjp
    redirect_to new_payjp_path, alert: 'クレジットカード情報を登録してください' unless current_user.customer.present?
  end

end

app/controllers/purchased/items_controller.rb
class Purchased::ItemsController < ApplicationController
  before_action :move_to_sign_in

  def index
    @items = Item.where(buyer_id: current_user.id).where(trading_status: 1)
  end

  def show
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/completed/items_helper.rb
module Completed::ItemsHelper
end

app/helpers/in_progress/items_helper.rb
module InProgress::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/listings/items_helper.rb
module Listings::ItemsHelper
end

app/helpers/order_status/items_helper.rb
module OrderStatus::ItemsHelper
end

app/helpers/purchase/items_helper.rb
module Purchase::ItemsHelper
end

app/helpers/purchase_pre/items_helper.rb
module PurchasePre::ItemsHelper
end

app/helpers/purchased/items_helper.rb
module Purchased::ItemsHelper
end

app/views/order_status/items/_index.html.erb
<li>
  <%= link_to "/order_status/items/#{item.id}", class: "mypage-item-link" do %>
    <figure>
      <% item.images.first(1).each do |content| %>
       <%= image_tag content.image %>
      <% end %>
    </figure>
    <div class="mypage-item-body">
      <time>
        <i class="icon-time"></i>
        <span><%= item.updated_at.to_s(:purchased_at) %></span>
      </time>
      <div class="clearfix">
        <div class="l-left">販売利益</div>
        <div class="l-right">¥ <%= number_with_delimiter(item.benefit_from_selling.floor) %></div>
      </div>
    </div>
    <i class="fas fa-angle-right"></i>
  <% end %>
</li>

app/views/order_status/items/index.html.erb
<%= render "shared/header" %>
<div class="l-container">
  <div class="l-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">売上履歴</h2>
      <ul class="mypage-item-list">
        <% @items.each do |item| %>
          <%= render partial: "index", locals: { item: item } %>
        <% end %>
      </ul>
    </section>
  </div>
<%= render "shared/sidebar" %>
</div>
<%= render "shared/seller-button" %>
<%= render "shared/footer" %>

app/views/order_status/items/sales_tra_lim.html.erb
<%= render "shared/header" %>
<div class="l-container">
  <div class="l-content">
    <section class="l-chapter-container">
    <h2 class="l-chapter-head">売上金の振込申請期限</h2>
      <ul class="mypage-item-list">
        <li class="mypage-nav-list-item clearfix">
          <div class="l-left">
            <div class="mypage-item-text">2019年3月28日</div>
          </div>
          <div class="l-right">¥ 322</div>
        </li>
      </ul>
    </section>
  </div>
<%= render "shared/sidebar" %>
</div>
<%= render "shared/seller-button" %>
<%= render "shared/footer" %>

app/views/order_status/items/sales_transfer.html.erb
<%= render "shared/header" %>
<div class="l-container clearfix">
  <div class="l-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">売上・振込申請</h2>
      <ul class="mypage-nav-list">
        <li>
          <div class="mypage-nav-list-item clearfix">
            <div class="l-left">
              現在の売上金
            </div>
            <div class="l-right">
                <% t = 0 %> 
                <% @items.each do |a_price|%>
                <% t = a_price.benefit_from_selling.floor + t %>
                <% end %>
              ¥ <%= number_with_delimiter(t) %>
            </div>
          </div>
        </li>
        <li>
          <%= link_to order_status_items_path, class: "mypage-nav-list-item clearfix" do %>
          <div>
            売上履歴
          </div>
          <div>
            <i class="fas fa-angle-right"></i>
          </div>
          <% end %>
        </li>
        <li>
          <a href="/mains/sales_tra_lim/" class="mypage-nav-list-item clearfix">
            <div>
              売上金の振込申請期限
            </div>
            <div>
              <i class="fas fa-angle-right"></i>
            </div>
          </a>
        </li>
      </ul>
    </section>
    <section class="l-chapter-container sales-transfer-second">
      <ul class="mypage-nav-list">
        <li>
          <a href="/mains/sales_tra_bank/" class="mypage-nav-list-item clearfix">
            <div>
              振込申請して現金を受け取る
            </div>
            <div>
              <i class="fas fa-angle-right"></i>
            </div>
          </a>
        </li>
        <li>
          <a href="/mains/sales_tra_history/" class="mypage-nav-list-item clearfix">
            <div>
              振込申請履歴
            </div>
            <div>
              <i class="fas fa-angle-right"></i>
            </div>
          </a>
        </li>
        <li>
          <a href="/jp/help_center/category/11/" class="mypage-nav-list-item clearfix" target="_blank">
            <div>
              振込申請スケジュール
            </div>
            <div>
              <i class="fas fa-angle-right"></i>
            </div>
          </a>
        </li>
      </ul>
    </section>
  </div>
<%= render "shared/sidebar" %>
</div>
<%= render "shared/seller-button" %>
<%= render "shared/footer" %>

app/views/order_status/items/show.html.erb
<%= render "shared/header"%>
<main class="l-container-item-status clearfix">
  <div class="l-content">
  <section class="l-chapter-container">
    <h2 class="l-chapter-head">取引画面</h2>
      <div class="transact-attention">
        <h3><i class="material-icons">check</i><span>取引が完了しました</span></h3>
        <p>このたびはメルカリのご利用ありがとうございました</p>
       </div>
       <ul class="transact-guide text-right">
        <li>
          <a href="/jp/help_center/category/11/" target="_blank"><span>販売代金の受け取りについて</span>
            <i class="material-icons">keyboard_arrow_right</i>
          </a>
        </li>
      </ul>
      <div class="message-container">
        <div class="message-content"> 
          <form action="https://www.mercari.com/jp/transaction/message/m38566204988/" method="POST" class="message-form">
            <input type="hidden" name="__csrf_value" value="0644e11ac11535f6ce17a85a24cf789dcfb1049d472209b13a8e9da33a515307a6ecb510ffa1d6c80c59470f9a493e48c506103a0118ad15071cc4ccc7f05d910">
            <p>取引メッセージの内容は、必要に応じて事務局で確認しています</p>
            <input type="hidden" name="item_id" value="m38566204988">
            <textarea type="text" name="body" value="" class="textarea-default" ></textarea>
            <button type="submit" class="message-submit btn-default btn-gray" >
              <span>取引メッセージを送る</span>
            </button>
          </form>
        </div>
      </div>
      <div class="message-content">
        ※お困りの際は
          <a href="/jp/help_center/category/2/" target="_blank">
            よくある質問
          </a>
        をご確認ください。
      </div>
    </section>
  </div>
  <%= render "shared/order_status_sidebar"%>
</main>
<%= render "shared/footer" %>